### ISSUE TITLE
Create hifi figma mock

### ISSUE THREAD

**Issue by aislinggallagher** [aislinggallagher/PluggableAuthGroup25#1]

**Comment by doylea35** [comment]
Completed 2 drafts, edited copy is better suited to the clients requirements.
https://www.figma.com/file/AfAyCyemUN6EdcOTogXcfd/SwEng-Hifi?node-id=0%3A1&t=c6G0ffSu1edqcxzs-1
edited copy:
https://www.figma.com/file/f26Q20A9ShaJEaPWjyTYAX/SwEng-Hifi-Edited?node-id=0%3A1&t=F37nbNQK6JZtuJ21-1
